### ISSUE TITLE
Error: weapons-on-back does not have a resource manifest (fxmanifest.lua)

### ISSUE THREAD

**Issue by Lampa4L** [minipunch/weapons-on-back#15]
Hey guys can you help me?

[resources:weapons-on] Warning: weapons-on-back-1.2 does not have a resource manifest (fxmanifest.lua)

**Comment by minipunch** [comment]
You can ignore that warning because the `__resource.lua` works just the same

**Comment by Lampa4L** [comment]
Yes but It couldn't start so How I can fix it?

**Comment by minipunch** [comment]
> Yes but It couldn't start so How I can fix it?

Are you certain it didn't start? It should start just fine and nobody else has complained about this
