### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by TheAxe99** [minipunch/weapons-on-back#8]
Couldn't load resource weapons-on-back-1.1: Couldn't load resource weapons-on-back-1.1 from resources:/weapons-on-back-1.1/: Could not open resource metadata file resources:/weapons-on-back-1.1//__resource.lua.

**Comment by minipunch** [comment]
@TheAxe99 You need put the wrong folder in your ``resources`` folder. Only put the folder that contains the ``__resource.lua`` file in. Not the one with the README.

**Comment by TheAxe99** [comment]
i did this but still the same error

**Comment by TheAxe99** [comment]
nvm fixed it
