### ISSUE TITLE
Add this "GetSelectedPedWeapon(me) ~= wep_hash" to prevent the "resmon" increase suddenly when took out the gun

### ISSUE THREAD

**Issue by CaptainAvenger** [minipunch/weapons-on-back#9]
https://github.com/minipunch/weapons-on-back/blob/aca375b3fed6fbc4a499a97d29c4ca780f18c688/weapons-on-back/cl_weapons-on-back.lua#L56
`if not attached_weapons[wep_name] then`
Change to
`if not attached_weapons[wep_name] and GetSelectedPedWeapon(me) ~= wep_hash then `

**Comment by minipunch** [comment]
Nice @CaptainAvenger 

Good find and fix!

It did seem to be attaching and removing the weapon over and over again if it was equipped which was caused the high CPU usage.

I'll go ahead and patch this now and push a live version.

Thanks again!
